modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT License"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Quantum Cubes"
description = "Portable dimensions inside a block. Build your base in a quantum cube and carry it anywhere."
authors = "titammods"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neoforge_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "[${minecraft_version},)"
    ordering = "NONE"
    side = "BOTH"
